### ISSUE TITLE
UX issue!

### ISSUE THREAD

**Issue by alexjp** [garuda-linux/startpage-v2#1]
Looks awesome and Catppuccin is one my favorite color scheme (after Tokyo Night)

But things look a bit unreadable with the wallpapers!!

![image](https://github.com/user-attachments/assets/07550ea3-df06-4a27-86cf-1f8f407102e0)

Congrats :)

**Comment by dr460nf1r3** [comment]
I agree this is an issue - will be providing an option to switch the fonts to a darker tone soon.

**Comment by dr460nf1r3** [comment]
Should be fixed with this commit, the new option basically adds a darker card background so text can still be read.
